config/routes.rb
Rails.application.routes.draw do
  root 'complete#index'
  devise_for :users
  resources :user, only: [:edit, :update]
  resources :complete, only: [:index]
    
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :list, only: [:new, :create, :edit, :update, :destroy] do
  resources :card, except: :index do
  resources :complete, only: [:create,:destroy]
  end
  end




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  belongs_to :complete, dependent: :destroy, optional: true
  validates :title, length: { in: 1..255 }
  validates :memo,  length: { maximum: 1000}
  validates :where, length: { in: 1..255 }
end

app/models/complete.rb
class Complete < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  
  has_many :cards, dependent: :destroy
  validates :time_zone, presence: true
  validates :title, length: {in: 1..255}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
has_many :lists, dependent: :destroy
has_many :completes,dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true, length: { maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/card_controller.rb
class CardController < ApplicationController
before_action :set_card, only: [:show, :edit, :update,:destroy]
  def new
    @card = Card.new
    @list = List.find_by(id: params[:list_id])
  
  end

  def create
   
    @card = Card.new(card_params)
   
    if @card.save
   

      redirect_to :root
    else
      render action: :new
    end
    
  end

  def show
    
  end

  def edit
    @lists = List.where(user: current_user)
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to :root
    else
      render action: :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to :root
  end



  private
  def set_card
    @card = Card.find_by(id: params[:id])
  end

  def card_params
    params.require(:card).permit(:title, :memo, :list_id,:where)
  end
end

app/controllers/complete_controller.rb
class CompleteController < ApplicationController
  before_action :set_card, only: [:create, :destroy]
  before_action :set_list, only: [:create, :destroy]
 require "date"
  def index
  @lists = List.where(user: current_user)
  
@user = current_user
if @user.total_login.blank? 
  @user.total_login = 1
end

if @user.login_date.blank? | @user.continous_login.blank?
@user.login_date = Date.today
@user.continous_login = 1
end

if @user.login_date == Date.today 

elsif @user.login_date + 1 == Date.today
@user.total_login += 1
@user.continous_login += 1
@user.login_date = Date.today
completes = Complete.where(user_id: @user.id)
completes.delete_all
else
  @user.total_login += 1
@user.continous_login = 1
@user.login_date = Date.today
completes = Complete.where(user_id: @user.id)
completes.delete_all
end
@user.save
 

end

def create
@complete = Complete.create(user_id: current_user.id, card_id: @card.id)

end

  def destroy
    @complete = Complete.find_by(user_id: current_user.id,card_id: @card.id)
    @complete.destroy
  end
  private

  def set_card
    @card = Card.find(params[:card_id])
  end

  def set_list
    @list = List.find_by(id: @card.list_id)
  end
 
end

app/controllers/list_controller.rb
class ListController < ApplicationController
before_action :set_list, only: [:edit, :update, :destroy]

  def new
    @list = List.new
  end

  def create
     @list = List.new(list_params)
     
     @list[:time_zone]=@list[:time_zone].delete("0")
     @list[:time_zone]=@list[:time_zone].delete("""\"")
     @list[:time_zone]=@list[:time_zone].delete(",")
     
    if @list.save
      redirect_to :root
    else
      render action: :new
    end
  end

  def edit

  end

  def update
    
    
  
    if @list.update(list_params)
      @list[:time_zone]=@list[:time_zone].delete("0")
      @list[:time_zone]=@list[:time_zone].delete("""\"")
      @list[:time_zone]=@list[:time_zone].delete(",")
      @list.save
      redirect_to :root

    else
      render action: :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to :root
  end
  private
  def list_params
    
    params.require(:list).permit(:title,time_zone: []).merge(user: current_user)
    
 
     
  end


  def set_list
  @list =List.find_by(id: params[:id])

  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def edit
    @user= User.find_by(id: current_user.id)
  end

  def update
    @user= User.find_by(id: current_user.id)
    if @user.update_attributes(user_params)
      redirect_to :root
    else
      render action: :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:name,:login_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/card/edit.html.haml
.cardeditPgae
  .container
    = form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f|
      - if @card.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      .cardeditForm_title
        = f.label :title,"あなたが継続したいこと "
        = f.text_field :title, autofocus: true, class: "form-control", placeholder: "例：スクワッド"
        .cardnewForm_title.cardformWhere
          = f.label :where, "どの場所でやるか"
          = f.text_field :where, autofocus: true, class: "form-control", placeholder: "例：家の中"
        .cardnewForm_memo
          = f.label :memo,"目標達成の条件"
          = f.text_field :memo, autofocus: true, class: "form-control", placeholder: "例：15回できたら"
      .text-center= f.submit "更新する", class: "submitBtn"

app/views/card/new.html.haml
.cardnewPgae
  .container
    = form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f|
      = f.hidden_field :list_id, value: @list.id
      - if @card.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      .cardnewForm_title
        = f.label :title,"あなたが継続したいこと "
        = f.text_field :title, autofocus: true, class: "form-control", placeholder: "例：スクワッド"
      .cardnewForm_title.cardformWhere
        = f.label :where, "どの場所でやるか"
        = f.text_field :where, autofocus: true, class: "form-control", placeholder: "例：家の中"
      .cardnewForm_memo
        = f.label :memo,"目標達成の条件"
        = f.text_field :memo, autofocus: true, class: "form-control", placeholder: "例：15回できたら"
        .text-center= f.submit "作成する", class: "submitBtn"

app/views/card/show.html.haml
.carddetailPage
  .container
    .cardContents
      .cardContents_title
        %div 継続させたいこと
        %h2= @card.title
      .cardContents_title
        %div どこでやるか
        %h2= @card.where
      .cardContents_memo
        %div 目標
        %div= @card.memo
      .cardContents_listStatus
        %div 普段行っていること
        %div= @card.list.title
      .cardContents_btnArea
        = link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn"
        = link_to '削除をする', list_card_path(@card.list, @card), class: "text-danger delete_btn", method: :delete, data: { confirm: "このカードを削除して大丈夫ですか?" }

app/views/complete/_complation.haml
%div{id: "done#{card.id}"}
  -@complete = Complete.find_by(user_id: current_user.id, card_id: card.id)
  - unless @complete.present?
    = link_to(list_card_complete_index_path(list,card), class: "card_link", style: "color:black;",method: :post,remote: true,) do
      .card
        継続させたいこと
        %h3.card_title= card.title
        どこでやるか
        %h3.card_where= card.where
        目標
        %h4.card_memo= card.memo     
  - else
    = link_to(list_card_complete_path(list,card,@complete.id), class: "card_link", style: "color:black;",method: :delete,remote: true)do
      .card
        %h3.card_title= card.title
        は完了しました。

app/views/complete/create.js.erb
$('#done<%=@card.id%>').html("<%= j(render partial: 'complete/complation', locals: { card: @card, list: @list}) %>");

app/views/complete/destroy.js.erb
$('#done<%=@card.id%>').html("<%= j(render partial: 'complete/complation', locals: { card: @card, list: @list}) %>");

app/views/complete/index.html.haml
.topPage
  .listWrapper
    - @lists.each do |list|
      .list
        .list_header
          .div_list
            時間帯
            %h4.list_header_timeZone= list.time_zone
          %h2.list_header_title= list.title 
          %h2.list_header_title 時に
          .list_header_action
            = link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" }
            = link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list))
        .cardWrapper
          - list.cards.each do |card|
            = render partial: 'complete/complation', locals: { card: card, list: list}
          .addCard
            %i.far.fa-plus-square
            = link_to "継続させたいことを結びつける", new_list_card_path(list), class: "addCard_link"
  .topIllustration
    .balloon1
      %p#balloon1_p.balloon1_p
        連続 #{@user.continous_login}日目 
        %br 
        合計 #{@user.total_login}日目
    = image_tag 'pixta_67204892_S (2).png',class:"topIllustration__samurai",id:'samurai'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title if_then_planning
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    
  %body
    = render 'partial/header' if current_user
    - if flash[:notice]
      .alert.alert-info
        = flash[:notice]
    - if flash[:alert]
      .alert.alert-danger
        = flash[:alert]
    = yield
    = javascript_include_tag 'application'
    
    -# , 'data-turbolinks-track': 'reload'

app/views/list/edit.html.haml
.listeditPage
  .container
    = form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f|
      - if @list.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      = f.label :title, "あなたが普段行っていること"
      = f.text_field :title, class: "form-control listName", placeholder: "リスト名"
      .listnewForm_time_zone
        .time 普段行っていることの時間帯
        %ul.time_ul
          %li.time_li
            = f.check_box :time_zone, {multiple: true},"朝"
            朝
          %li.time_li
            = f.check_box  :time_zone, {multiple: true},"昼"
            昼
          %li.time_li
            = f.check_box  :time_zone, {multiple: true},"夕方"
            夕方
          %li.time_li
            = f.check_box  :time_zone, {multiple: true},"夜"
            夜
      .text-center= f.submit "編集する", class: "submitBtn"

app/views/list/new.html.haml
.listnewPage
  .container
    = form_with model: @list, url: { action: :create }, class: "new_list", local: true do |f|
      - if @list.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      .listnewForm_title
        = f.label :title,"普段行っていること"
        = f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "例：コーヒーを飲む" 
      .listnewForm_time_zone
        .time 普段行っていることの時間帯
        %ul.time_ul
          %li.time_li
            = f.check_box :time_zone, {multiple: true},"朝"
            朝
          %li.time_li
            = f.check_box  :time_zone, {multiple: true},"昼"
            昼
          %li.time_li
            = f.check_box  :time_zone, {multiple: true},"夕方"
            夕方
          %li.time_li
            = f.check_box  :time_zone, {multiple: true},"夜"
            夜
        .text-center= f.submit "作成する", class: "submitBtn"

app/views/partial/_header.html.haml
%body
  %header.header
    %nav.nav
      %ul.header_menu
        %li.nav-link= link_to current_user.name, edit_user_path(current_user.id)
        %li.header_menu_title= link_to "if_then_planning", root_path, class: "nav-link"
        %li
          %ul.header_menu_inner
            %li= link_to "普段行っていること", new_list_path, class: "nav-link listNew"
            %li= link_to "サインアウト", destroy_user_session_path, class: "nav-link",method: :delete

app/views/top/index.html.haml
.topPage
  .listWrapper
    - @lists.each do |list|
      .list
        .list_header
          .div_list
            時間帯
            %h4.list_header_timeZone= list.time_zone
          %h2.list_header_title= list.title 
          %h2.list_header_title 時に
          .list_header_action
            = link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" }
            = link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list))
        #done.cardWrapper
          - list.cards.each do |card|
            = render partial: 'top/complation', locals: { card: card}
          .addCard
            %i.far.fa-plus-square
            = link_to "継続させたいことを結びつける", new_list_card_path(list), class: "addCard_link"
  .topIllustration
    .balloon1
      %p#balloon1_p.balloon1_p
        連続 #{@user.continous_login}日目 
        %br 
        合計 #{@user.total_login}日目
    = image_tag 'pixta_67204892_S (2).png',class:"topIllustration__samurai",id:'samurai'

app/views/user/edit.html.haml
.listeditPage
  .container
    = form_with model: @user, url: { action: :update }, html: { class: 'listForm' }, local: true do |f|
      - if @user.errors.any?
        %p.text-danger タイトルは1～255文字以内で入力してください
      = f.label :name
      = f.text_field :name, class: "form-control listName", placeholder: "リスト名"
      .text-center= f.submit "編集する", class: "submitBtn"